Sample for configuring Bigtable connection pool
GoogleCloudPlatform/java-docs-samples pull request #4600
Opened 2021-01-26 19:33 UTC by billyjacobson

Fixes #issue

> It's a good idea to open an issue first for discussion.

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] Please **merge** this PR for me once it is approved.

2021-02-09 15:40 UTC, kolea2 commented on bigtable/hbase/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java
> +  private static final String INSTANCE_ENV = "BIGTABLE_TESTING_INSTANCE";
inline please to be consistent with `GOOGLE_CLOUD_PROJECT` :)

2021-03-22 17:03 UTC, lesv requested changes

2021-03-22 17:03 UTC, lesv commented on bigtable/hbase/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java
> +  }
Does this get restored ever?

2021-03-22 17:08 UTC, billyjacobson commented on bigtable/hbase/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java
> +  }
I guess not in this test. Will update

2021-03-22 17:39 UTC, lesv commented on bigtable/hbase/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java
> +
Still need to restore this.

2021-03-22 19:21 UTC, lesv approved these changes

2021-03-22 19:34 UTC, merged