Rename code-of-conduct.md to CODE-OF-CONDUCT.md
GoogleCloudPlatform/java-docs-samples pull request #4633
Opened 2021-02-04 20:21 UTC by lesv

- [x] Please **merge** this PR for me once it is approved.

2021-02-04 20:27 UTC, tbpg requested changes
I think it needs to be CODE_OF_CONDUCT.md?

2021-02-04 20:32 UTC, lesv commented
@tbpg changed.

2021-02-04 20:52 UTC, JustinBeckwith approved these changes

2021-02-05 12:24 UTC, tbpg approved these changes

2021-02-05 17:30 UTC, eaball35 approved these changes

2021-02-05 17:30 UTC, merged