chore(functions): fix flaky tests + update dir property
GoogleCloudPlatform/java-docs-samples pull request #5305
Opened 2021-05-25 04:46 UTC by ace-n

This should fix #5250 and #5257

(I wasn't able to reproduce them locally, but this makes the tests themselves more fault-tolerant.)

2021-05-25 18:42 UTC, lesv requested changes

2021-05-25 19:05 UTC, ace-n commented on functions/helloworld/hello-gcs/src/test/java/functions/ExampleIT.java
> +          }
See `retryOnResultPredicate` on [this page](https://resilience4j.readme.io/docs/retry).

Happy to link to that in a comment, if that would help?

2021-05-25 19:05 UTC, ace-n commented on functions/helloworld/hello-gcs/src/test/java/functions/ExampleIT.java
> +          }
Yes - `maxAttempts(8)`

2021-05-25 19:05 UTC, ace-n commented on functions/helloworld/hello-pubsub/src/test/java/functions/ExampleIT.java
> +        })
As above - `maxAttempts(8)`

2021-05-25 19:13 UTC, lesv commented on functions/helloworld/hello-gcs/src/test/java/functions/ExampleIT.java
> +          }
Yes

2021-05-25 19:34 UTC, ace-n commented on functions/helloworld/hello-gcs/src/test/java/functions/ExampleIT.java
> +          }
Done, PTAL?

2021-05-25 19:50 UTC, lesv approved these changes

2021-05-25 19:51 UTC, lesv commented
# Lint
```
#
# functions/helloworld/hello-gcs
#

[ERROR] src/test/java/functions/ExampleIT.java:[96,24] (naming) LambdaParameterName: Lambda parameter name '__' must match pattern '^[a-z]([a-z0-9][a-zA-Z0-9]*)?$'.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (default-cli) on project functions-hello-gcs: You have 1 Checkstyle violation. -> [Help 1]


#
# functions/helloworld/hello-pubsub
#

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (default-cli) on project functions-hello-pub-sub: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-checkstyle-plugin:jar:3.1.2 -> org.apache.maven:maven-core:jar:3.0 -> org.apache.maven:maven-aether-provider:jar:3.0 -> org.sonatype.aether:aether-api:jar:1.7: Failed to read artifact descriptor for org.sonatype.aether:aether-api:jar:1.7: Could not transfer artifact org.sonatype.aether:aether-parent:pom:1.7 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/org/sonatype/aether/aether-parent/1.7/aether-parent-1.7.pom.part (No such file or directory) -> [Help 1]
```

2021-05-26 01:52 UTC, ace-n commented
@lesv thanks - see [this `checkstyle` change](https://github.com/GoogleCloudPlatform/java-repo-tools/pull/254).

2021-05-26 01:54 UTC, lesv approved these changes

2021-05-26 20:20 UTC, merged