Added Cloud Support API v2 Code Samples
GoogleCloudPlatform/java-docs-samples pull request #6718
Opened 2022-02-16 19:22 UTC by eenclona-google

This PR has code samples for Cloud Support API v2. We cannot include unit tests as part of this PR since it involves sensitive information (private key of service accounts / gcp support account). However, this code is tested well internally and it works. Product team suggested to include this in the repo though so that they can easily embed it in the public docs. Thanks!

- [x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [x] `pom.xml` parent set to latest `shared-configuration`
- [x] Appropriate changes to README are included in PR
- [x] API's need to be enabled to test (tell us)
- [x] Environment Variables need to be set (ask us to set them)
- [x] **Tests** pass:   `mvn clean verify` **required**
- [x] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [x] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [x] Please **merge** this PR for me once it is approved.

2022-02-16 19:34 UTC, lesv commented on support/cloud-client/pom.xml
> +  <!-- FIXME change it to the project's website -->
Who should be fixing this?

2022-02-16 20:36 UTC, lesv requested changes
Please read and comply with: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md

* Missing License & copyright
* No parent pom
* `String.format` paths
* Start w/ latest artifacts
* Java 1.8 minimum
* Use ADC algorithm, don't use json keys directly.

2022-02-16 20:36 UTC, lesv commented on support/cloud-client/src/main/java/com/gcpsupport/samples/CreateCase.java
> +        String PARENT_RESOURCE = "projects/<---project id--->";
It's better in Java to use `String.format("projects/%s",projectId);`

2022-02-16 20:36 UTC, lesv commented on support/cloud-client/src/main/java/com/gcpsupport/samples/CreateCase.java
> +            return new CloudSupport.Builder(httpTransport, jsonFactory, requestInitializer).build();
If you use the ADC algorithm, this might change

2022-02-16 20:36 UTC, lesv commented on support/cloud-client/src/main/java/com/gcpsupport/samples/CreateCase.java
> +            System.out.println("Created case's name is: " + newCaseResponse.getName());
Not sure these need newlines, but I could see that being easier to read.  Your line length might be too much.

2022-02-16 20:36 UTC, lesv commented on support/cloud-client/src/main/java/com/gcpsupport/samples/GetCase.java
> +    final static String PRIVATE_KEY_JSON_PATH = "/<---path--->/key.json";
ADC algorithm mentioned earlier.

2022-02-16 20:36 UTC, lesv commented on support/cloud-client/src/main/java/com/gcpsupport/samples/CreateCase.java
> +package com.gcpsupport.samples;
Missing license & copyright in all files

2022-02-16 20:36 UTC, lesv commented on support/cloud-client/src/main/java/com/gcpsupport/samples/CreateCase.java
> +package com.gcpsupport.samples;
We usually go with `com.example.gcpsupport` or `gcpsupport`

2022-02-16 20:36 UTC, lesv commented on support/cloud-client/pom.xml
> +  <artifactId>cloud-client</artifactId>
com.example is common for us.

2022-02-16 20:36 UTC, lesv commented on support/cloud-client/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Copyright & license ?

2022-02-16 20:36 UTC, lesv commented on support/cloud-client/pom.xml
> +  <name>cloud-client</name>
This should reference the parent pom.  https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md#project-dependencies

2022-02-16 20:36 UTC, lesv commented on support/cloud-client/pom.xml
> +    </reporting>
Use the parent pom for this, get the sample styleguide

2022-02-16 20:37 UTC, lesv commented
@eenclona-google Please visit `github/` and add yourself to the googlecloudplatform & googleapis groups.

2022-02-16 20:40 UTC, lesv commented
Also, your tests are missing.  Definitely please fix that.

2022-02-16 20:41 UTC, lesv commented
@eenclona-google Welcome to Google - please fix the requested changes, feel free to reach out to me or @Neenu1995 if you have questions or need some help.

2022-02-16 20:50 UTC, eenclona-google commented
Hi @lesv ! Thanks for the comments. Will take a look at these and fix. Re: tests, I wasn't sure how to write those since I was originally using service account private keys and wasn't aware of ADC. I'll review this and try to include the unit tests as well. Will probably ping you with some questions as I go! I hope that's okay. Thanks a lot! :)

2022-02-22 21:40 UTC, eenclona-google commented
Hi @lesv ! I just updated my PR with the changes requested. I hope this is good! Thanks!

2022-02-22 21:50 UTC, lesv commented
@eenclona-google It looks like things didn't run correctly.  You might wish to look at the results from snippet-bot, Lint, Java 8, and Java 11 and fix them.  Let me know if you need me to enable an API or provide something new.

2022-02-22 21:53 UTC, lesv commented
# Lint
- for reference, we use [google style](https://google.github.io/styleguide/javaguide.html) with an extended line length and the ability to disable.

```
#
# support/cloud-client
#

[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[1] (header) RegexpHeader: Line does not match expected header line of '^\W+\*?\W*Copyright 20\d\d Google (Inc\.|LLC)$'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[26,1] (imports) CustomImportOrder: Wrong lexicographical order for 'java.io.InputStreamReader' import. Should be before 'java.io.Reader'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[30,1] (imports) CustomImportOrder: Extra separation in import group before 'com.google.api.client.googleapis.javanet.GoogleNetHttpTransport'
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[30,1] (imports) CustomImportOrder: Wrong lexicographical order for 'com.google.api.client.googleapis.javanet.GoogleNetHttpTransport' import. Should be before 'java.util.Collections'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[31,1] (imports) CustomImportOrder: Wrong lexicographical order for 'com.google.api.client.http.HttpRequestInitializer' import. Should be before 'java.util.Collections'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[32,1] (imports) CustomImportOrder: Wrong lexicographical order for 'com.google.api.client.http.HttpTransport' import. Should be before 'java.util.Collections'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[33,1] (imports) CustomImportOrder: Wrong lexicographical order for 'com.google.api.client.json.JsonFactory' import. Should be before 'java.util.Collections'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[34,1] (imports) CustomImportOrder: Wrong lexicographical order for 'com.google.api.client.json.gson.GsonFactory' import. Should be before 'java.util.Collections'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[35,1] (imports) CustomImportOrder: Wrong lexicographical order for 'com.google.api.services.cloudsupport.v2beta.CloudSupport' import. Should be before 'java.util.Collections'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[36,1] (imports) CustomImportOrder: Wrong lexicographical order for 'com.google.api.services.cloudsupport.v2beta.model.CloudSupportCase' import. Should be before 'java.util.Collections'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[37,1] (imports) CustomImportOrder: Wrong lexicographical order for 'com.google.auth.http.HttpCredentialsAdapter' import. Should be before 'java.util.Collections'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[38,1] (imports) CustomImportOrder: Wrong lexicographical order for 'com.google.auth.oauth2.GoogleCredentials' import. Should be before 'java.util.Collections'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[39,1] (imports) CustomImportOrder: Wrong lexicographical order for 'com.google.api.client.json.JsonObjectParser' import. Should be before 'java.util.Collections'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[45,5] (indentation) Indentation: 'member def modifier' has incorrect indentation level 4, expected level should be 2.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[45,11] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[47,5] (indentation) Indentation: 'method def modifier' has incorrect indentation level 4, expected level should be 2.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[49,9] (indentation) Indentation: 'try' has incorrect indentation level 8, expected level should be 4.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[51,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[54,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[55,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[55,20] (naming) AbbreviationAsWordInName: Abbreviation in name 'PARENT_RESOURCE' must contain no more than '1' consecutive capital letters.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[55,20] (naming) LocalVariableName: Local variable name 'PARENT_RESOURCE' must match pattern '^[a-z]([a-z0-9][a-zA-Z0-9]*)?$'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[58,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[59,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[59,20] (naming) AbbreviationAsWordInName: Abbreviation in name 'CASE' must contain no more than '1' consecutive capital letters.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[59,20] (naming) LocalVariableName: Local variable name 'CASE' must match pattern '^[a-z]([a-z0-9][a-zA-Z0-9]*)?$'.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[61,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[63,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[64,9] (indentation) Indentation: 'try rcurly' has incorrect indentation level 8, expected level should be 4.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[65,13] (indentation) Indentation: 'catch' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[66,9] (indentation) Indentation: 'catch rcurly' has incorrect indentation level 8, expected level should be 4.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[68,5] (indentation) Indentation: 'method def rcurly' has incorrect indentation level 4, expected level should be 2.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[72,5] (indentation) Indentation: 'method def modifier' has incorrect indentation level 4, expected level should be 2.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[74,9] (indentation) Indentation: 'try' has incorrect indentation level 8, expected level should be 4.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[76,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[77,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[82,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[84,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[86,13] (indentation) Indentation: 'try' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[88,9] (indentation) Indentation: 'try rcurly' has incorrect indentation level 8, expected level should be 4.
[ERROR] src/main/java/com/example/gcpsupport/UpdateCase.java:[89,13] (indentation) Indentation: 'catch' child has incorrect indentation level 12, expected level should be 6.
[ERROR] src/main/java/com/example/gcpsuppor [...]

2022-02-24 20:49 UTC, eenclona-google commented
I pushed to fix style errors and update the test suite. Only thing left is for me to coordinate with the customer care team to make your GCP projects support enabled. Once that's done, the tests that I wrote should all pass in your end as well.

2022-03-01 20:59 UTC, lesv commented
@eenclona-google Please get lint & snippet-bot check to pass.

2022-03-07 13:41 UTC, closed without merging