Add Java docs samples for KMS key import.
GoogleCloudPlatform/java-docs-samples pull request #7441
Opened 2022-11-17 19:05 UTC by bdhess

Fixes #issue

> It's a good idea to open an issue first for discussion.

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] Please **merge** this PR for me once it is approved.

2022-11-17 23:23 UTC, anguillanneuf requested changes
Please rerun `mvn com.coveo:fmt-maven-plugin:format` to fix lint issues and update mismatching region tags.

2022-11-17 23:23 UTC, anguillanneuf commented on kms/src/main/java/kms/CreateKeyForImport.java
> +import com.google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionAlgorithm;
Import order.

2022-11-17 23:23 UTC, anguillanneuf commented on kms/src/main/java/kms/CreateKeyForImport.java
> +// [END kms_create_crypto_key]
Wrong end region tag.

2022-11-28 19:40 UTC, anguillanneuf commented on kms/src/main/java/kms/CreateKeyForImport.java
> +import com.google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionAlgorithm;
I fixed it for you.

2022-11-28 19:40 UTC, anguillanneuf commented on kms/src/main/java/kms/CreateKeyForImport.java
> +// [END kms_create_crypto_key]
I fixed it for you.

2022-11-28 19:40 UTC, anguillanneuf approved these changes

2022-11-28 20:45 UTC, meltsufin approved these changes

2022-12-06 18:33 UTC, merged