test: add retries to dlp tests
GoogleCloudPlatform/java-docs-samples pull request #7747
Opened 2023-03-16 00:48 UTC by kweinmeister

Fixes #7728

2023-03-16 01:20 UTC, realjordanna requested changes

2023-03-16 01:20 UTC, realjordanna commented on dlp/snippets/src/test/java/dlp/snippets/TestBase.java
> +  @Rule public final MultipleAttemptsRule multipleAttemptsRule = new MultipleAttemptsRule(5);
add a comment as to why this is needed and why 5 was chosen. it's okay if your answer is 5 is a guess, or there is some known upper limit on what it should be...

2023-03-16 16:24 UTC, kweinmeister commented
> This sample was flaky due to the `dlp.inspectContent(request)` asynchronous task failed. It may be better to show users how to handle that error than just rerun the test.

That works for me. I can remove the "Fixes" link, if we don't want to resolve the issue with this improvement.

@realjordanna any thoughts? Would your team be able to also address the more granular issue as @averikitsch described?

2023-03-18 01:58 UTC, realjordanna commented
That makes sense to me ... I'm looking through the flake at https://source.cloud.google.com/results/invocations/789c3d20-dad7-4ee3-960d-8d9d4b193109/targets/cloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/log, and the error in the failing test isn't useful because it is truncated. I can't actually see what the server returned to the test because of the truncation. Catching the exception would allow us to get a better log statement to see what's going on. If we have the project_number from the test I could grab logs internally possibly, but this method is not known to be flaky on the backend side. I have identical http based tests that look like this that are not flaking. Do we know what the deadline is set too? Maybe it's too short?

2023-03-22 12:50 UTC, kweinmeister commented
Thank you @realjordanna and @averikitsch. We can merge this for now, and if see we continued flakiness, we can do a more thorough investigation.

2023-03-22 19:40 UTC, merged