Implemented sample for Reidentify Free TextWith Fpe Using Surrogate
GoogleCloudPlatform/java-docs-samples pull request #7829
Opened 2023-04-04 05:04 UTC by bhavika-dhanwani

Fixes #issue

> It's a good idea to open an issue first for discussion.

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] Please **merge** this PR for me once it is approved.

2023-04-04 05:15 UTC, realjordanna approved these changes

2023-04-04 22:50 UTC, micheldavid requested changes
no major issues. thanks!

2023-04-06 18:00 UTC, micheldavid approved these changes

2023-04-17 13:14 UTC, bhavika-dhanwani commented
@micheldavid As we have introduced new environment variable "DLP_DEID_UNWRAPPED_KEY", the test checks will fail. Please help us setting the mentioned environment variable.

2023-04-19 12:20 UTC, annadata commented on dlp/snippets/src/test/java/dlp/snippets/DeIdentificationTests.java
> +        PROJECT_ID, "My phone number is PHONE_TOKEN(10):9617256398", "YWJjZGVmZ2hpamtsbW5vcA==");
Instead of hardcoding I suggest using a secret key generated by the test.

2023-04-19 12:31 UTC, annadata commented on dlp/snippets/README.md
> +- Set the `DLP_DEID_UNWRAPPED_KEY` environment variable to an unwrapped key. (Unwrapped key corresponds to a base-64 encoded random key having length of 128, 192, or 256 bits)
These changes are no longer needed.

2023-04-19 14:17 UTC, annadata approved these changes
LGTM

2023-04-19 16:10 UTC, merged