[DLP] Implemented a sample for Inspect String with Augmented InfoTypes
GoogleCloudPlatform/java-docs-samples pull request #7864
Opened 2023-04-10 05:37 UTC by bhavika-dhanwani

Implemented a sample for [augmenting built-in infoType detectors by including a built-in detector](https://cloud.google.com/dlp/docs/creating-custom-infotypes-dictionary#augment_a_built-in_infotype_detector)

- [X] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [X] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [X] **Tests** pass:   `mvn clean verify` **required**
- [X] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [X] Please **merge** this PR for me once it is approved.

2023-04-10 07:55 UTC, annadata commented on dlp/snippets/src/test/java/dlp/snippets/InspectTests.java
> +        "bdp-2059-is-31084", "patient: quasimodo");
Do not hardcode the projectId. Use PROJECT_ID like the other tests.

2023-04-10 07:55 UTC, annadata commented on dlp/snippets/src/main/java/dlp/snippets/InspectStringAugmentInfoType.java
> +                  CustomInfoType.Dictionary.WordList.newBuilder().addWords("quasimodo").build())
Please parameterise the words and send it from caller.

2023-04-10 07:55 UTC, annadata commented on dlp/snippets/src/main/java/dlp/snippets/InspectStringAugmentInfoType.java
> +    String textToInspect = "patient: quasimodo";
How about "The patients name is Quasimodo"

2023-04-10 07:55 UTC, annadata commented on dlp/snippets/src/main/java/dlp/snippets/InspectStringAugmentInfoType.java
> +      // Construct the custom infotype detector associated with the word list.
// Construct a custom infotype detector by augmenting the PERSON_NAME detector with a word list

2023-04-20 04:44 UTC, Sita04 requested changes

2023-04-20 04:44 UTC, Sita04 commented on dlp/snippets/src/main/java/dlp/snippets/InspectStringAugmentInfoType.java
> +// [START dlp_inspect_augment_infotypes]
Move this region tag to line 18, before the import statements.

2023-04-20 04:44 UTC, Sita04 commented on dlp/snippets/src/main/java/dlp/snippets/InspectStringAugmentInfoType.java
> +// [START dlp_inspect_augment_infotypes]
Move this region tag to line 18, before the import statements.

2023-04-20 04:44 UTC, Sita04 commented on dlp/snippets/src/main/java/dlp/snippets/InspectStringAugmentInfoType.java
> +  // Inspects the provided text.
Can the description be a bit more elaborate, mentioning the use of a custom word to detect.

2023-04-20 04:44 UTC, Sita04 commented on dlp/snippets/src/main/java/dlp/snippets/InspectStringAugmentInfoType.java
> +    // The string to be additionally matched
```suggestion
    // The string to be additionally matched.
```

2023-04-20 04:44 UTC, Sita04 commented on dlp/snippets/src/main/java/dlp/snippets/InspectStringAugmentInfoType.java
> +      //  Construct a custom infotype detector by augmenting the PERSON_NAME detector with a word
```suggestion
      // Construct a custom infotype detector by augmenting the PERSON_NAME detector with a word
```

2023-04-20 09:23 UTC, bhavika-dhanwani commented on dlp/snippets/src/main/java/dlp/snippets/InspectStringAugmentInfoType.java
> +      //  Construct a custom infotype detector by augmenting the PERSON_NAME detector with a word
Resolved the suggested changes

2023-04-20 12:08 UTC, Sita04 approved these changes

2023-04-20 15:34 UTC, merged