[DLP] Update an existing job trigger
GoogleCloudPlatform/java-docs-samples pull request #7981
Opened 2023-05-03 12:03 UTC by bhavika-dhanwani

Implementation of [Updating an existing job trigger](https://cloud.google.com/dlp/docs/creating-job-triggers#update_an_existing_job_trigger)

## Checklist

- [X] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [X] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [X] **Tests** pass:   `mvn clean verify` **required**
- [X] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [X] Please **merge** this PR for me once it is approved

2023-05-05 07:36 UTC, soumya92 requested changes

2023-05-05 07:36 UTC, soumya92 commented on dlp/snippets/src/main/java/dlp/snippets/TriggersPatch.java
> +      // Send the scan request and process the response
Update this comment; we are not sending a scan request, just updating a job trigger.

Job Trigger updates do not immediately cause scans, and job trigger results are not returned in api but need to be fetched separately later.

2023-05-05 07:36 UTC, soumya92 commented on dlp/snippets/src/main/java/dlp/snippets/TriggersPatch.java
> +      // Combine configurations into a request for the service.
"// Update the job trigger with the new configuration"

2023-05-05 07:36 UTC, soumya92 commented on dlp/snippets/src/main/java/dlp/snippets/TriggersPatch.java
> +      // Configure the inspection job we want the service to perform.
We should just remove this comment, I don't think it's adding any value.

2023-05-05 14:05 UTC, Sita04 requested changes

2023-05-05 14:05 UTC, Sita04 commented on dlp/snippets/src/main/java/dlp/snippets/TriggersPatch.java
> +      FieldMask fieldMask = FieldMask.newBuilder()
+1 A doc link on constructing these paths would also be helpful

2023-05-08 12:38 UTC, bhavika-dhanwani commented on dlp/snippets/src/main/java/dlp/snippets/TriggersPatch.java
> +      FieldMask fieldMask = FieldMask.newBuilder()
> +1 A doc link on constructing these paths would also be helpful

Done

2023-05-11 18:56 UTC, soumya92 approved these changes

2023-05-17 17:25 UTC, Sita04 approved these changes

2023-05-17 17:49 UTC, merged