Feature/create ruleset
GoogleCloudPlatform/java-docs-samples pull request #8218
Opened 2023-06-01 19:48 UTC by chasinandrew

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [X] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [X] `pom.xml` parent set to latest `shared-configuration`
- [X] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [X] **Tests** pass:   `mvn clean verify` **required**
- [X] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [X] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [X] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [X] Please **merge** this PR for me once it is approved

2023-06-02 19:18 UTC, anguillanneuf commented
@chasinandrew i don't have all the context for content-warehouse. do you have a bug like b/271994104 where your team has been properly onboarded? 

cc: @gericdong

2023-06-02 20:25 UTC, chasinandrew commented
hey @anguillanneuf I raised a bug for this request b/285617061.

2023-06-02 21:23 UTC, anguillanneuf commented on content-warehouse/src/main/java/contentwarehouse/v1/CreateRuleSet.java
> +// [START contentwarehouse_createruleset]
please update sample region tag to match internal sample region tag database. see b/285617061#comment2.

2023-06-02 22:08 UTC, anguillanneuf commented on content-warehouse/src/main/java/contentwarehouse/v1/CreateRuleSet.java
> +          .setActions(0, (Action) action).build();
use `addActions()` instead.

2023-06-02 22:31 UTC, anguillanneuf commented on content-warehouse/src/main/java/contentwarehouse/v1/CreateRuleSet.java
> +      }
```suggestion
      listRuleSetsPagedResponse.iterateAll().forEach(
          (ruleSet -> System.out.println(ruleSet))
      );
```

2023-06-05 16:07 UTC, anguillanneuf requested changes
One more nit and you're good to go! Thanks for contributing :-)

2023-06-05 16:07 UTC, anguillanneuf commented on content-warehouse/src/main/java/contentwarehouse/v1/CreateRuleSet.java
> +// [START contentwarehouse_create_rule_set]
Move this tag to line 18. We want to display the full sample including imports when we publish this sample.

2023-06-05 17:35 UTC, anguillanneuf approved these changes

2023-06-05 17:36 UTC, anguillanneuf approved these changes

2023-06-05 17:36 UTC, merged