docs: add samples for using timeouts
GoogleCloudPlatform/java-docs-samples pull request #8255
Opened 2023-06-13 12:10 UTC by olavloite

Adds samples for running queries and updates with timeouts. This is one of the most frequently asked questions for the Spring Data Spanner project.

2023-06-13 18:10 UTC, averikitsch requested changes

2023-06-13 18:10 UTC, averikitsch commented on spanner/spring-data/src/main/java/com/example/spanner/SpannerRepositorySample.java
> +  public void runRepositoryTimeoutExample() {
based on the style guide https://googlecloudplatform.github.io/samples-style-guide/, we typically have samples in individual files with separate region tags. Can you update?

2023-06-13 18:14 UTC, averikitsch commented
We also expect tests for each sample

2023-06-14 13:18 UTC, olavloite commented
> We also expect tests for each sample

There are no tests or test infrastructure at all set up for this project, which makes adding tests for these samples difficult.

2023-06-22 16:42 UTC, averikitsch commented
> > We also expect tests for each sample
> 
> There are no tests or test infrastructure at all set up for this project, which makes adding tests for these samples difficult.

It is a part of our policy for samples to have tests: https://googlecloudplatform.github.io/samples-style-guide/#testing. Without tests samples are not maintainable. The [api-spanner-java](https://github.com/orgs/GoogleCloudPlatform/teams/api-spanner-java) team owns the spanner samples, therefore without explicit consent from this owner we may not be able to accept these samples.

2023-06-23 05:34 UTC, olavloite commented
> api-spanner-java

Specifically the Spring Data Spanner project is maintained by a different team.

@meltsufin Could you chime in here, please? Do you know whether there's a specific reason that there are no tests set up for these samples? Or are there any plans for doing so?

2023-09-26 16:07 UTC, meltsufin commented
> > api-spanner-java
> 
> Specifically the Spring Data Spanner project is maintained by a different team.
> 
> @meltsufin Could you chime in here, please? Do you know whether there's a specific reason that there are no tests set up for these samples? Or are there any plans for doing so?

We have [tests](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample/src/test/java/com/example) for Spring Data Spanner samples the we maintain in spring-cloud-gcp. We do not maintain java-docs-samples repo, however.

2023-10-06 16:20 UTC, anguillanneuf approved these changes

2023-10-06 17:37 UTC, olavloite commented
@anguillanneuf Would you mind merging this PR? I don't think I have permission to merge anything in this repo.

2023-10-25 22:30 UTC, minherz reviewed
I am not familiar with the demand. There is no issue external or internal referenced here.
I would suggest to avoid adding region tags before you register it and to follow region tag guidelines. I cannot add internal go-link here. Please, search for "region tag" for internal doc.

2023-10-25 22:30 UTC, minherz commented on spanner/spring-data/src/main/java/com/example/spanner/SpannerRepositoryTimeoutSample.java
> +// [START spanner_spring_data_repository_timeout_sample]
Please, do not create new region tag without registering it with http://devrel

2024-09-03 14:43 UTC, minherz commented
@olavloite, thank you very much for your contribution. Our requirement for tests means to reduce the maintenance burden over code samples. We will be happy to help you with setting up necessary infrastructure configurations.

Before you being, please review other [spanner samples](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/spanner) to see what they use.
You might want to consider implementing the test as a unit test by mocking underlying infrastructure because the goal of the code sample is to be complaint with the framework's and libraries it is using and not to validate the end-to-end behavior of the sample vs. Google APIs.
Feel free to reach out by mail or Chat. I've invited you to the "Java samples review requests" space.

2024-09-05 07:26 UTC, olavloite commented
Closing for now due to the testing discussion.

2024-09-05 07:26 UTC, closed without merging