Feature/set acl
GoogleCloudPlatform/java-docs-samples pull request #8461
Opened 2023-07-22 22:00 UTC by chasinandrew

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [X] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [X] `pom.xml` parent set to latest `shared-configuration`
- [X] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [X] **Tests** pass:   `mvn clean verify` **required**
- [X] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [X] Please **merge** this PR for me once it is approved

2023-07-24 16:41 UTC, Sita04 requested changes
Thanks for the sample. PTAL at the comments and also the failing tests.

2023-07-24 16:41 UTC, Sita04 commented on content-warehouse/src/main/java/contentwarehouse/v1/SetAcl.java
> +  public static void setAcl() throws IOException,
This should be main method.

2023-07-24 16:41 UTC, Sita04 commented on content-warehouse/src/main/java/contentwarehouse/v1/SetAcl.java
> +  public static void setAcl(String projectId, String location,
Kindly add a method comment.

2023-07-24 16:41 UTC, Sita04 commented on content-warehouse/src/main/java/contentwarehouse/v1/SetAcl.java
> +            .setId(userId).build()).build();
```suggestion
            .setId(userId).build())
            .build();
```

2023-07-24 16:41 UTC, Sita04 commented on content-warehouse/src/main/java/contentwarehouse/v1/SetAcl.java
> +        .setRole(role).build();
```suggestion
        .setRole(role)
        .build();
```

2023-07-24 16:41 UTC, Sita04 commented on content-warehouse/src/main/java/contentwarehouse/v1/SetAcl.java
> +        setAclResponse = documentServiceClient.setAcl(setAclRequest);
This line can be moved out of the if..else loop.

2023-07-24 16:41 UTC, Sita04 commented on content-warehouse/src/main/java/contentwarehouse/v1/SetAcl.java
> +        setAclResponse = documentServiceClient.setAcl(setAclRequest);
```suggestion
        
```

2023-07-24 16:41 UTC, Sita04 commented on content-warehouse/src/test/java/contentwarehouse/v1/SetAclTest.java
> +  private static final String DOCUMENT_ID = "06rubracospg8";
Kindly remove these values from here and include it as part of the CI env vars.

2023-07-24 16:41 UTC, Sita04 commented on content-warehouse/src/test/java/contentwarehouse/v1/SetAclTest.java
> +  }
```suggestion
  
  @BeforeAll
  public static void setup() {
    requireEnvVar("GOOGLE_CLOUD_PROJECT");
    requireEnvVar("GOOGLE_APPLICATION_CREDENTIALS");
    MEMBERS.add(0, USER_ID);
  }
   
  @Before
  public void setUp() {
    bout = new ByteArrayOutputStream();
    out = new PrintStream(bout);
    originalPrintStream = System.out;
    System.setOut(out);
  }
```

Checking required env variables and adding the User ID should be part of the `BeforeAll` annotation, which executes exactly once before the tests are run.
Including it as part of the`Before` annotation would make them run before every test is executed.

2023-07-24 16:41 UTC, Sita04 commented on content-warehouse/src/test/java/contentwarehouse/v1/SetAclTest.java
> +  private static final ArrayList<String> MEMBERS = new ArrayList<>();
```suggestion
  private static ArrayList<String> MEMBERS = new ArrayList<>();
```

2023-07-24 16:41 UTC, Sita04 commented on content-warehouse/src/test/java/contentwarehouse/v1/SetAclTest.java
> +
Include a new line here.

2023-08-22 20:54 UTC, closed without merging

2023-08-22 20:54 UTC, chasinandrew commented
Closing this PR as this sample is deprioritized