iam_create_service_account_java
GoogleCloudPlatform/java-docs-samples pull request #9288
Opened 2024-04-16 08:22 UTC by ssvir

## Description

Fixes

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [ ] Please **merge** this PR for me once it is approved

2024-04-18 03:13 UTC, Sita04 requested changes
Thanks for the snippets! PTAL at the comments.

2024-04-18 03:13 UTC, Sita04 commented on iam/api-client/src/main/java/iam/snippets/RenameServiceAccount.java
> +  public static void renameServiceAccount(String projectId, String serviceAccountName, String displayName) throws IOException {
@hegemonic what are your thoughts? Should we update the region tag as well.

2024-04-18 03:13 UTC, Sita04 commented on iam/api-client/src/main/java/iam/snippets/DeleteServiceAccountKey.java
> +    String serviceAccountKey = "key-name";
The service account key has only an `id`. Kindly update all instances of key name to key id.

`String serviceAccountKeyId = "service-account-key-id";`

2024-04-18 03:13 UTC, Sita04 commented on iam/api-client/src/main/java/iam/snippets/DeleteServiceAccountKey.java
> +              .replace(serviceAccountName, serviceAccountEmail);
Is it possible to pass the service account email directly in KeyName instead of replacing it?

2024-04-18 03:13 UTC, Sita04 commented on iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java
>      assertThat(got, containsString("Created service account: " + SERVICE_ACCOUNT));
Assert using the returned value from ` CreateServiceAccount.createServiceAccount`

2024-04-18 03:13 UTC, Sita04 commented on iam/api-client/src/main/java/iam/snippets/RenameServiceAccount.java
>      }
Return the updated service account.

2024-04-18 03:13 UTC, Sita04 commented on iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java
> +    assertThat(got, containsString(renameTo));
Use the returned value from `RenameServiceAccount.renameServiceAccount()` to assert.

2024-04-18 03:13 UTC, Sita04 commented on iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java
>      assertThat(got, containsString("Deleted key:"));
Consider retrieving the service account to confirm that the key has been deleted.

2024-04-18 03:13 UTC, Sita04 commented on iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java
>      assertThat(got, containsString("Deleted service account:"));
Consider retrieving the service account to confirm that the account has been deleted.

2024-04-18 11:58 UTC, ssvir commented on iam/api-client/src/main/java/iam/snippets/CreateServiceAccount.java
> +      serviceAccount = iamClient.createServiceAccount(request);
Hey, yeap we can, but all test strategies are based on asserting messages what we expect and comparing  to what we put into System.out.println, at least for void methods

2024-04-18 12:17 UTC, ssvir commented on iam/api-client/src/main/java/iam/snippets/RenameServiceAccount.java
> +  public static void renameServiceAccount(String projectId, String serviceAccountName, String displayName) throws IOException {
Referring to PatchServiceAccountRequest docs: "_The service account patch request.
 
  You can patch only the `display_name` and `description` fields. You must use
  the `update_mask` field to specify which of these fields you want to patch.
 
  Only the fields specified in the request are guaranteed to be returned in
  the response. Other fields may be empty in the response._" 
It looks like with this method, we can update only _display_name_ and _description_, so I think we can leave this naming, with __updateServiceAccount__ method we can only update _display_name_  too.

2024-04-22 19:43 UTC, hegemonic commented
I have a big-picture concern about this PR: Is someone also rewriting the other IAM code samples in this repo to use the GAPIC libraries?

If so, that's great! This migration is long overdue.

If not, I don't think we should merge this PR. It would be extremely confusing if some pages in the IAM docs told you to use the Google API Client Library for Java, and other pages told you to use the Cloud Client Library for Java. We need to update _all_ of the samples for each language, not just _some_ of them.

2024-04-23 10:36 UTC, m-strzelczyk commented
Hey @hegemonic ! Thanks for your vigilance in this regard :) I'm happy to inform that it's a coordinated effort to move all Java and Python IAM samples that are still using the old libraries to the new ones. Please reach out to me if you're interested in more details.

2024-04-23 23:27 UTC, hegemonic commented on iam/api-client/src/main/java/iam/snippets/RenameServiceAccount.java
> +  public static void renameServiceAccount(String projectId, String serviceAccountName, String displayName) throws IOException {
I'm okay with either option.

2024-04-23 23:28 UTC, hegemonic commented
@m-strzelczyk Fantastic! Very glad to hear it 😀 

Can you let me know when you're mostly done with the IAM samples, so that we can update the [client libraries page](https://cloud.google.com/iam/docs/reference/libraries) as well?

2024-04-24 16:54 UTC, Sita04 commented on iam/api-client/src/main/java/iam/snippets/DeleteServiceAccountKey.java
> +      //See, https://cloud.google.com/iam/docs/creating-managing-service-account-keys?hl=en#deleting
In all these comment lines, kindly leave a leading space for readability.

2024-04-24 16:54 UTC, Sita04 commented on iam/api-client/src/main/java/iam/snippets/DeleteServiceAccountKey.java
> +      String serviceAccountEmail = serviceAccountName +"@"+ projectId + ".iam.gserviceaccount.com";
Use String.format to construct.

2024-04-24 16:54 UTC, Sita04 commented on iam/api-client/src/main/java/iam/snippets/DeleteServiceAccount.java
> +              .concat(".iam.gserviceaccount.com");
Use String.format to construct for better readability. Applies to all snippets.

2024-04-24 16:54 UTC, Sita04 commented on iam/api-client/src/main/java/iam/snippets/RenameServiceAccount.java
> +  public static void renameServiceAccount(String projectId, String serviceAccountName, String displayName) throws IOException {
Fair enough. No strong opinions on this.

2024-04-25 12:48 UTC, merged