feat: add compute reservation create sample
GoogleCloudPlatform/java-docs-samples pull request #9503
Opened 2024-08-29 13:45 UTC by TetyanaYahodska

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [ ] Please **merge** this PR for me once it is approved

2024-09-04 16:11 UTC, Sita04 requested changes

2024-09-04 16:50 UTC, TetyanaYahodska commented on compute/cloud-client/src/test/java/compute/reservation/ReservationIT.java
>      assertThat(stdOut.toString()).contains("Deleted reservation: " + RESERVATION_NAME);
Thank you! Will add this assertion after adding getResevation method in the next PR

2024-09-05 10:32 UTC, TetyanaYahodska commented
Disabled tests in the Hyperdisk class because it cause error after several runs per day.  Will enable it in the last PR for reservation.

2024-09-05 15:38 UTC, Sita04 approved these changes
Please address the comment before merging

2024-09-05 15:38 UTC, Sita04 commented on compute/cloud-client/src/test/java/compute/disks/HyperdisksIT.java
>    @Test
If the disk is not being deleted, please mark this test as disabled as well and add a comment.

2024-09-05 15:39 UTC, Sita04 commented on compute/cloud-client/src/test/java/compute/reservation/ReservationIT.java
>      assertThat(stdOut.toString()).contains("Deleted reservation: " + RESERVATION_NAME);
Kindly add a comment stating this reason.

2024-09-05 15:49 UTC, merged