feat(compute): add compute reservation get
GoogleCloudPlatform/java-docs-samples pull request #9507
Opened 2024-09-01 16:01 UTC by TetyanaYahodska

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [ ] Please **merge** this PR for me once it is approved

2024-09-06 15:50 UTC, Sita04 requested changes

2024-09-06 15:50 UTC, Sita04 commented on compute/cloud-client/src/main/java/compute/reservation/CreateReservationForInstanceTemplate.java
> +    // The URI of the instance template with GLOBAL Location
```suggestion
    // The URI of the instance template with GLOBAL location
```

2024-09-06 15:50 UTC, Sita04 commented on compute/cloud-client/src/main/java/compute/reservation/CreateReservationForInstanceTemplate.java
> +    // The URI of the instance template with REGIONAL Location
```suggestion
    // The URI of the instance template with REGIONAL location
```

2024-09-06 18:39 UTC, TetyanaYahodska commented on compute/cloud-client/src/test/java/compute/reservation/ReservationIT.java
Thank you

2024-09-06 19:27 UTC, TetyanaYahodska commented on compute/cloud-client/src/test/java/compute/reservation/ReservationIT.java
> +    try (ReservationsClient reservationsClient = ReservationsClient.create()) {
Tried to do it in this way, but got errors. Didn't see such implementation for the other classes. Could we left it as is?

2024-09-11 22:34 UTC, Sita04 approved these changes

2024-09-12 06:31 UTC, merged