feat(compute): add compute reservation create shared
GoogleCloudPlatform/java-docs-samples pull request #9535
Opened 2024-09-24 20:06 UTC by TetyanaYahodska

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [ ] Please **merge** this PR for me once it is approved

2024-10-04 18:06 UTC, TetyanaYahodska commented on compute/cloud-client/src/main/java/compute/reservation/CreateSharedReservation.java
> +        .putProjectMap("CONSUMER_PROJECT_ID_2", ShareSettingsProjectConfig.newBuilder().build())
In the test envaironment we don't have possibility to create additional projects to implement this feature. For this reason we have different implementation for this sample. And for test we mocked everything.

2024-10-04 18:07 UTC, TetyanaYahodska commented on compute/cloud-client/src/main/java/compute/reservation/CreateSharedReservation.java
> +    // Create an instance of your class, passing in the real client
Thank you!

2024-10-16 13:40 UTC, m-strzelczyk requested changes

2024-10-16 13:40 UTC, m-strzelczyk commented on compute/cloud-client/src/main/java/compute/reservation/CreateSharedReservation.java
> +        .putProjectMap("CONSUMER_PROJECT_ID_2", ShareSettingsProjectConfig.newBuilder().build())
Please indicate, those CONSUMER_PROJECT_ID_1 and _2 are the projects that will have access to the reservation.

2024-10-16 13:40 UTC, m-strzelczyk commented on compute/cloud-client/src/main/java/compute/reservation/CreateSharedReservation.java
> +    String projectId = "YOUR_PROJECT_ID";
Make sure to highlight the fact, that this project MUST be allowlisted in `compute.sharedReservationsOwnerProjects` org policy. See more at: https://cloud.google.com/compute/docs/instances/reservations-shared#shared_reservation_constraint

2024-10-16 13:40 UTC, m-strzelczyk commented on compute/cloud-client/src/test/java/compute/reservation/ReservationIT.java
> +    when(mockOperation.getStatus()).thenReturn(Operation.Status.DONE);
Add explenation why we need to mock + what would have to be changes if someone wants to test this code without mocking.

2024-10-28 14:44 UTC, Sita04 approved these changes
One nit. LGTM.
Kindly get Maciej's LGTM before merging.

2024-10-29 12:34 UTC, m-strzelczyk approved these changes

2024-10-29 12:51 UTC, merged