docs(samples): Dataflow to Apache Iceberg with dynamic destinations
GoogleCloudPlatform/java-docs-samples pull request #9645
Opened 2024-11-04 23:06 UTC by VeronicaWasson

## Description

Add snippet for Iceberg dynamic destinations

- Add a snippet that shows the use of [https://github.com/apache/beam/issues/32365](dynamic destinations) when writing to Apache Iceberg from Dataflow, This is a new feature in [Beam 2.60](https://github.com/apache/beam/releases/tag/v2.60.0).

- Refactor integration tests to remove the assumption of exactly 1 destination table.

Relevant doc bug: b/371047621

## Checklist

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [ ] Please **merge** this PR for me once it is approved

2025-01-16 20:08 UTC, iennae commented
@code-review-assist review

2025-01-16 20:09 UTC, iennae commented
@code-review-assist walkthrough

2025-01-29 17:18 UTC, VeronicaWasson commented
@iennae @kweinmeister Should I address anything from the code review bot?

2025-02-05 18:10 UTC, chamikaramj reviewed
This is great! Thanks for adding this example.

LGTM

2025-02-05 18:10 UTC, chamikaramj commented on dataflow/snippets/pom.xml
> +    <apache_beam.version>2.60.0</apache_beam.version>
+1 but noting that Dataflow will be upgrading Iceberg to the latest version anyways.

2025-02-06 17:13 UTC, VeronicaWasson commented on dataflow/snippets/pom.xml
> +    <apache_beam.version>2.60.0</apache_beam.version>
I bumped the version

2025-02-14 00:39 UTC, telpirion requested changes
Hello @VeronicaWasson ! This sample looks really good. I have just a handful of comments for you. Please take a look at your earliest convenience.

Tip: I recommend formatting this sample similar to other Java samples. [Here's a recently merged sample that follows all style guidance.](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/vertexai/snippets/src/main/java/vertexai/gemini/ChatDiscussion.java)

2025-02-18 22:59 UTC, VeronicaWasson commented on dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergDynamicDestinations.java
> +  public static PipelineResult.State main(String[] args) {
Fixed

(fwiw, I've gotten some conflicting guidance on this in previous Dataflow code snippets)

2025-02-18 23:00 UTC, VeronicaWasson commented on dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergDynamicDestinations.java
> +  // [END dataflow_apache_iceberg_dynamic_destinations]
Fixed

2025-02-18 23:01 UTC, VeronicaWasson commented on dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergDynamicDestinations.java
> +    return pipeline;
Since I'm no longer returning the result, there's nothing to check here. (If the pipeline fails, the IT will fail.)

2025-02-18 23:01 UTC, VeronicaWasson commented on dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergDynamicDestinations.java
> +    var options = PipelineOptionsFactory.fromArgs(args).withValidation().as(Options.class);
Fixed

2025-02-18 23:01 UTC, VeronicaWasson commented on dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergDynamicDestinations.java
> +  static final List<String> TABLE_ROWS = Arrays.asList(
Fixed

2025-02-18 23:04 UTC, VeronicaWasson commented on dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergDynamicDestinations.java
> +  public static PipelineResult.State main(String[] args) {
This pattern is idiomatic for Dataflow / Apache Beam. To run the pipeline, the user passes in command line arguments that get parsed via the PipelineOptions class.

e.g.: 

https://beam.apache.org/documentation/programming-guide/#pipeline-options-cli

2025-02-18 23:04 UTC, VeronicaWasson commented on dataflow/snippets/src/test/java/com/example/dataflow/ApacheIcebergIT.java
> +    PipelineResult.State state = ApacheIcebergDynamicDestinations.main(
Done

2025-02-18 23:04 UTC, VeronicaWasson commented on dataflow/snippets/src/test/java/com/example/dataflow/ApacheIcebergIT.java
> +
Fixed

2025-02-18 23:10 UTC, VeronicaWasson commented on dataflow/snippets/src/test/java/com/example/dataflow/ApacheIcebergIT.java
>    public void setUp() throws IOException {
The sample writes records to an Iceberg catalog, so the IT tests whether the records were added successfully. 

Previously I was doing this in a roundabout way (printing the records to stdout first) but this version seems more direct.

2025-02-18 23:17 UTC, VeronicaWasson commented on dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergDynamicDestinations.java
> +  public static Pipeline createPipeline(Options options) {
Thanks for pointing that out, I added some more comments.

2025-02-27 17:57 UTC, telpirion approved these changes

2025-02-27 19:23 UTC, merged