feat(compute): add compute snapshot schedule attach sample.
GoogleCloudPlatform/java-docs-samples pull request #9791
Opened 2024-12-02 13:30 UTC by TetyanaYahodska

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [ ] Please **merge** this PR for me once it is approved

2024-12-27 07:16 UTC, Sita04 requested changes

2024-12-27 12:31 UTC, TetyanaYahodska commented on compute/cloud-client/src/main/java/compute/snapshotschedule/AttachSnapshotScheduleToDisk.java
> +    try (DisksClient disksClient = DisksClient.create()) {
Thank you! Added comment

2024-12-27 12:32 UTC, TetyanaYahodska commented on compute/cloud-client/src/main/java/compute/snapshotschedule/AttachSnapshotScheduleToDisk.java
> +      Operation response = disksClient.addResourcePoliciesAsync(request).get(1, TimeUnit.MINUTES);
Thank you! Fixed timeout to 3 min

2024-12-27 12:32 UTC, TetyanaYahodska commented on compute/cloud-client/src/main/java/compute/snapshotschedule/CreateSnapshotSchedule.java
> +// [START compute_snapshot_schedule_create]
I need this classes for testing.

2024-12-27 12:32 UTC, TetyanaYahodska commented on compute/cloud-client/src/main/java/compute/snapshotschedule/DeleteSnapshotSchedule.java
> +// [START compute_snapshot_schedule_delete]
I need this classes for testing.

2024-12-27 12:33 UTC, TetyanaYahodska commented on compute/cloud-client/src/main/java/compute/snapshotschedule/RemoveSnapshotScheduleFromDisk.java
> +    // Name of the snapshot schedule you want to attach.
Thank you! Fixed

2024-12-27 12:33 UTC, TetyanaYahodska commented on compute/cloud-client/src/main/java/compute/snapshotschedule/RemoveSnapshotScheduleFromDisk.java
> +                      .setZone(zone)
Thank you! Fixed

2024-12-27 14:18 UTC, TetyanaYahodska commented on compute/cloud-client/src/test/java/compute/snapshotschedule/SnapshotScheduleIT.java
> +    assertThat(status).isEqualTo(Status.DONE);
Removed not related tests and used a mock client to test code.

2024-12-28 15:57 UTC, Sita04 approved these changes

2024-12-30 09:05 UTC, merged